# Generated by Django 3.2.7 on 2021-09-03 08:53

from django.db import migrations, models
import library_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('library_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='default/default.jpg', upload_to=library_site.models.book_directory_path),
        ),
    ]
