# Generated by Django 3.2.7 on 2021-09-03 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_site', '0005_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id']},
        ),
    ]
